### ISSUE TITLE
[Bug]: Search functionality is not working fine ! 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [codeaashu/DevDisplay#101]
### What happened?

I found a BUG 🐞

https://github.com/user-attachments/assets/67ad9507-172a-48bf-af33-de663e77a8f7

As you can see in video

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sawan-Kushwah** [comment]
Can you assign me i want to work on this

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support**: If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!
