### ISSUE TITLE
[style]: Can we change the position of theme button on different media 

### ISSUE THREAD

**Issue by amanpoddar-dev12** [codeaashu/DevDisplay#103]
### What's the style idea?

We need to improve the theme button position on different media   
In desktop size, we can adjust the position of the theme button around the search bar.
on the mobile view it will be the same

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mefisto04** [comment]
hey @amanpoddar-dev12 i want to contribute in this, can you assign this to me

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support**: If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!
