### ISSUE TITLE
[Feat]: Improve Pagination Experience with Loading Animation

### ISSUE THREAD

**Issue by SurajSakhare100** [codeaashu/DevDisplay#105]
### What feature?

I have an idea 
Description:
Currently, when the **user clicks the "Next" button for pagination**, the **page scrolls to the top**. This behavior **disrupts** the **user experience**. Instead, I propose the following enhancements:
**Loading Animation**: On clicking the "Next" button, display a loading animation that indicates the next set of content is being fetched, without scrolling to the top.

Pagination on Same Screen: The pagination should remain visible in the same viewport as the current content, ensuring a smoother experience as users navigate between pages. This will improve usability and maintain focus on the content.

By implementing these changes, we will create a more seamless and user-friendly experience. 
**Can you please assign this issue to me? I would love to work on it.**

### Add screenshots

Add screenshots

https://github.com/user-attachments/assets/ffb0f7e8-dd52-4153-8e1a-98ff5ffb2c2e

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SurajSakhare100** [comment]
https://github.com/user-attachments/assets/847712b2-96a7-4aa3-895d-55df6aa03635

I wanted to let you know that **I've addressed the issue** with the **loader component** in our project.
If there are any issues or adjustments needed, please let me know, and I'll be happy to resolve them.

If everything looks good, may I proceed to **create a pull request for these changes?**

Additionally, I would appreciate it if you could add a label for **GSSOC**  extension **level 2 or 3**, based on the impact of these improvements.

**Comment by codeaashu** [comment]
Do it @SurajSakhare100 hurry up! man

**Comment by SurajSakhare100** [comment]
@codeaashu  i made PR but there are some issue

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support**: If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!
