### ISSUE TITLE
[Feat]: Design a better and Responsive Footer for the application

### ISSUE THREAD

**Issue by dhruvjain23** [codeaashu/DevDisplay#106]
### What feature?

I can design and develop a interactive and responsive footer for your application which can enhance the good looking website. 

Kindly assigns me this issue under hacktoberfest and hacktoberfest-accepted labels . @codeaashu 

### Add screenshots

Add screenshots

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support**: If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!

**Comment by codeaashu** [comment]
hey @dhruvjain23 let's start working on this feature
