### ISSUE TITLE
[Bug]: Fix overlapping buttons

### ISSUE THREAD

**Issue by dalvishruti14** [codeaashu/DevDisplay#115]
### What happened?

I found a BUG 🐞
![image](https://github.com/user-attachments/assets/4bfdbbd8-829e-4827-83ad-09acea04cbb8)
Buttons are overlapping. 
Please assign this task to me.

### Add screenshots

Add screenshots

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support**: If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!
