### ISSUE TITLE
[Feat]: Discussion forum for all Devs

### ISSUE THREAD

**Issue by AayushiJapsare15** [codeaashu/DevDisplay#117]
### What feature?

We will create a Discussion Forum feature to create a vibrant community space where developers can ask questions, share knowledge, and engage in discussions on various development topics.

This will make the DevDisplay a platfrom from developer seeking partner for hackathon , events, personal project, product development etc.

Main Advantage of this feature is:
- If i am a user trying to connect to a developer with similar skill i might find it hesty and lengthy to contact each of them separately since we cant be just sure after requesting just one. 
- Its better to have a forum where i will put my proposal and interested developers can interact , this also increases the chances of seeking knowledge from experienced developers. 
- The forum will provide an opportunity for less experienced developers to seek guidance and insights from seasoned professionals, fostering a culture of learning and mentorship within the community.
- By facilitating discussions around shared interests and goals, the forum will strengthen connections among developers, leading to long-term relationships and potential future collaborations.

we can even add constraints of your choice to maintain ethnicity.

This feature can increase the amount of active user on the site thus increasing its reach.

If you found this feature interesting , I would like you to assign it to me.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AayushiJapsare15** [comment]
@codeaashu please consider this feature and assign it to me.

**Comment by codeaashu** [comment]
Amazing idea, Start working on this features
but before that add your profile on DevDisplay
It's is the first priority of contribution in DevDisplay

if you don't assign in this you will not be able to contribute on this project

**Comment by AayushiJapsare15** [comment]
Sure i will add my profile on DevDisplay. 
can you please add 'hacktoberfest-accepted' label as well since it is crucial for hacktober and level label

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support**: If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!

**Comment by codeaashu** [comment]
Hey @AayushiJapsare15 

We're inviting you to work on this issue 573
https://github.com/codeaashu/DevDisplay/issues/573#issue-2682280137

& and join DevDisplay as a core team member.
