### ISSUE TITLE
[style]: Fix the overlapping theme icon and add hover effects for the profile boxes

### ISSUE THREAD

**Issue by AKSHATH99** [codeaashu/DevDisplay#118]
### What's the style idea?

We need to improve  the UI by removing the overlapping between the theme icon and the search bar . 
I would also like to apply hover effects to the profile boxes in the home page for more interactive UI experience . 

I would like to work on this issue under Hacktoberfest label 

### Add screenshots

Add screenshots
Need to fix the spacing here 
![Screenshot 2024-10-04 224034](https://github.com/user-attachments/assets/c23294fe-db3a-4a09-b48a-d06eec4b21e1)

Apply hover effects here 
![Screenshot 2024-10-04 224112](https://github.com/user-attachments/assets/d1593314-364e-43c4-ba47-5c0352b6b255)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AKSHATH99** [comment]
The overlapping  seem to be in responsiveness of that page

**Comment by codeaashu** [comment]
Start working on this features
but before that add your profile on DevDisplay
It's is the first priority of contribution in DevDisplay

if you don't assign in this you will not be able to contribute on this project

**Comment by AKSHATH99** [comment]
Okay . Will raise a issue

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support**: If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!
