### ISSUE TITLE
[Feat]: Adding contact us option also 

### ISSUE THREAD

**Issue by Aditijainnn** [codeaashu/DevDisplay#132]
### What feature?

Adding contact us/ rate us option also so that user can interact 
please assign this isuue to me under gssoc ext and hacktoberfest

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codeaashu** [comment]
Start working on this features

but before that add your profile on Devdisplay.
It's is the first priority of contribution in DevDisplay

if you don't assign in this you will not be able to contribute on this project

**Comment by Aditijainnn** [comment]
> Start working on this features
> 
> but before that add your profile on Devdisplay. It's is the first priority of contribution in DevDisplay
> 
> if you don't assign in this you will not be able to contribute on this project

ok

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support**: If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!
