### ISSUE TITLE
Feature:A Scroll to top Button

### ISSUE THREAD

**Issue by yours7himanshu** [codeaashu/DevDisplay#144]
### What feature?
@n33dhi 
We should create a button at the bottom of the website and by clicking that website it automatically scrolled to the top.

### Add screenshots

Add screenshots
![Screenshot from 2024-10-06 00-55-20](https://github.com/user-attachments/assets/1254d56f-7e89-403e-8219-35299fb8ac6a)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codeaashu** [comment]
Start working on this features
but before that add your profile on DevDisplay
It's is the first priority of contribution in DevDisplay

if you don't assign in this you will not be able to contribute on this project

**Comment by DeshDeepakKushwaha** [comment]
I can do this task.Can you assign this to me.

**Comment by yours7himanshu** [comment]
> Start working on this features but before that add your profile on DevDisplay It's is the first priority of contribution in DevDisplay
> 
> if you don't assign in this you will not be able to contribute on this project

Okay I will do that asap but there is not label of gsoc-ext and hacktoberfest-accepted and Level tag

**Comment by w0wayush** [comment]
If no one has done anything...
Can I work on this ??

Also please add hacktoberfest-accepted tags in it.
