### ISSUE TITLE
[Feat]: Adding scroll functionality for viewing skills of user

### ISSUE THREAD

**Issue by w0wayush** [codeaashu/DevDisplay#158]
### What feature?

In the current website the users can't navigate/scroll through the user skills tills end to see all his/her skills.

So please assign this to me (@w0wayush), I'm going to add a scrolling feature in which it becomes easy for users to scroll through all the user's skills.

Add labels of hacktoberfest, gsoc-ext and hacktoberfest-accepted and level tag also.

### Add screenshots

![Screenshot 2024-10-06 210708](https://github.com/user-attachments/assets/082cce82-589b-4bcb-9650-43c75aa02f23)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codeaashu** [comment]
Start working on this features
but before that add your profile on DevDisplay
It's is the first priority of contribution in DevDisplay

if you don't assign in this you will not be able to contribute on this project

**Comment by w0wayush** [comment]
Okay, I will add my profile and I have started working on that skill scrolling feature

Can you please add hacktoberfest-accepted, hacktoberfest, gssoc24, gssoc-ext labels to this issue

**Comment by w0wayush** [comment]
I added my profile in DevDisplay and also added the functionality, but even after that why close my PR??

**Comment by PARVNEMA** [comment]
Assign me this issue please

**Comment by w0wayush** [comment]
Created new PR #177 review it as I updated all the things as per your needs!!

**Comment by w0wayush** [comment]
Wow dude, I opened the issue and you merged other's PR 👏 HATS OFF

2nd time 👏

**Comment by PARVNEMA** [comment]
Bro i am from owners development team and he has asked to do that work and sorry for that bro from next time first asked to get assigned then do the work

**Comment by PARVNEMA** [comment]
@w0wayush  if you know how to do auth i can assign you one issue

**Comment by w0wayush** [comment]
@PARVNEMA so what if you are from owner's development team, can't you see when I opened this issue and who is assigned to do the task.

Leave it..

It's always the best PR that get's merged at the end. 😓

Yes, I know how to do auth can you please elaborate more what I have to do??

**Comment by PARVNEMA** [comment]
@w0wayush  i am really sorry for that

**Comment by PARVNEMA** [comment]
@w0wayush  we have to implement auth into some specific routes like opportunity hub did you know clerk or appwrite

**Comment by w0wayush** [comment]
@PARVNEMA it's okay bro, I have worked with clerk and next-auth if you want I can try to implement what you want

**Comment by PARVNEMA** [comment]
Comment me at issue 187
