### ISSUE TITLE
[style]: Add Zoom Effect on Card in Opportunity page

### ISSUE THREAD

**Issue by iamsohelx** [codeaashu/DevDisplay#161]
### What's the style idea?

hey @codeaashu We need to improve Cards in Opportunity page add some transition and smooth animation to improve user experience

### Add screenshots

Add screenshots
![ScaleCard](https://github.com/user-attachments/assets/6912d6a2-070c-4fc6-b439-f2ca61c287ac)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iamsohelx** [comment]
@codeaashu Could you please assign this task to me.

**Comment by codeaashu** [comment]
Start working on this features
but before that add your profile on DevDisplay
It's is the first priority of contribution in DevDisplay

if you don't assign in this you will not be able to contribute on this project

**Comment by iamsohelx** [comment]
@codeaashu Yeah sure brother

**Comment by iamsohelx** [comment]
@codeaashu Done brother, can i work on it now?

**Comment by iamsohelx** [comment]
@codeaashu heyy brother?

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support**: If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!

**Comment by codeaashu** [comment]
Check out the #issue475 ⬇
https://github.com/codeaashu/DevDisplay/issues/475#issue-2617410305

Get a #level3 on your open-source contribution.

Remember that ⚠ This issue will be closed on 31 October

**Comment by AE-Hertz** [comment]
@codeaashu can you please assign me this ?
