### ISSUE TITLE
[style]: Request to Modify Footer Alignment on About Page

### ISSUE THREAD

**Issue by akhil11sharma** [codeaashu/DevDisplay#162]
### What's the style idea?

We need to improve  I would like to propose changing the footer alignment on the About page from left-aligned to center-aligned. This adjustment will enhance the visual appeal of the webpage and provide a more balanced layout.

### Add screenshots

Add screenshots
![Uploading Screenshot 2024-10-07 at 9.56.36 AM.png…]()

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support**: If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!
