### ISSUE TITLE
[style]:  Enhance UI/UX of home page.

### ISSUE THREAD

**Issue by Mr-DK07** [codeaashu/DevDisplay#167]
### What's the style idea?

We need to improve  

### Add screenshots

Hey @codeaashu I want to make it more attractive and user friendly. I simply going to improve the design by adding some styling and color. I can add animation as well.

![Screenshot 2024-10-07 191611](https://github.com/user-attachments/assets/e5379df5-2916-4f5f-a045-010742525ab7)

Could you assign this task, so that I can start working on it.
And Please make sure to add label (gssoc-ext, hactoberfest, Level1, Level2, Level3).

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by codeaashu** [comment]
Start working on this features
but before that add your profile on DevDisplay
It's is the first priority of contribution in DevDisplay

if you don't assign in this you will not be able to contribute on this project

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support**: If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!
