### ISSUE TITLE
Feature Request: Numbered Pagination Instead of "Previous" and "Next" Buttons

### ISSUE THREAD

**Issue by ishap11** [codeaashu/DevDisplay#171]
### What feature?

Description:
I would like to request an enhancement for the pagination system. Currently, the navigation uses "Previous" and "Next" buttons to move between pages. I propose introducing a numbered pagination system, where users can click on specific page numbers (e.g., 1, 2, 3, etc.). Additionally, the "Next" button should be disabled when the user is on the last page, and the "Previous" button should be disabled when on the first page. This feature should be dynamic to improve navigation.

Proposed Feature:
Replace the "Previous" and "Next" buttons with clickable numbered pagination links.
Display the page numbers below the content, so users can directly select any page without having to scroll.
Fix the pagination bar at the bottom of the page, ensuring it's always visible regardless of how far a user scrolls.

Reasoning:
This enhancement would significantly improve user experience by allowing users to easily navigate to a specific page, eliminating the need to click through each page or scroll repeatedly. It would make navigation more efficient and user-friendly.

### Add screenshots

*CURRENTLY*
![image](https://github.com/user-attachments/assets/4cb285ab-d3c4-4a7c-9f12-c75ce691070c)

*FEATURE REQUEST*
![image](https://github.com/user-attachments/assets/3c055ba1-670e-43a7-ae91-fc4035251b89)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Ravijhabit** [comment]
Hi @ishap11, Can you assign me this issue ?

**Comment by Harshitraaaj** [comment]
I can add this feature . Assign me ASAP

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support**: If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!

**Comment by Harshitraaaj** [comment]
why are you not assigned me yet ?

**Comment by Harshitraaaj** [comment]
Am i assigned in this issue or not ? @avishek999 are U a owner of this repo

**Comment by avishek999** [comment]
Nope

**Comment by avishek999** [comment]
Nope @Harshitraaaj

**Comment by Himanshu-Lilhore** [comment]
@codeaashu  Can you assign this to me please.

**Comment by Harshitraaaj** [comment]
@codeaashu buddy assign me this issue

**Comment by VijeshVS** [comment]
@codeaashu 
Could I work on this issue? I've developed similar pagination functionality for my personal projects and could bring that experience to this task.
