### ISSUE TITLE
Feature Request : Add Clickable Location Links to Open Specific Locations in Google Maps

### ISSUE THREAD

**Issue by ishap11** [codeaashu/DevDisplay#172]
### What feature?

Description:
I would like to request a feature where, when a user clicks on a particular location provided on the website, it opens Google Maps and displays that specific location.

Proposed Feature:
Integrate Google Maps with clickable location links on the website.
When a location is clicked, the corresponding map should open in a new tab or window with the location highlighted.

Reasoning:
This feature would enhance the user experience by allowing users to quickly view the exact location on Google Maps without manually searching for it, improving the website's usability and interactivity.

### Add screenshots

![image](https://github.com/user-attachments/assets/d980ec32-53bd-4c7d-885e-f34c055d9b5e)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Arkyapatwa** [comment]
I would like to work on this feature under hacktoberfest.

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support**: If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!
