### ISSUE TITLE
[Feat]: Sign in with validation

### ISSUE THREAD

**Issue by isimarjitsingh** [codeaashu/DevDisplay#175]
### What feature?

I have an idea we should need to add sign in form with validation please give me that opportunity because i am perfectly fit for that role as i know react and we add firebase for authentication. Gssoc extd

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support**: If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!
