### ISSUE TITLE
[style]: On home page there is missing transition on hover to tags

### ISSUE THREAD

**Issue by vishvboda** [codeaashu/DevDisplay#176]
### What's the style idea?

On the home page for every profile's tags category have no transition and icon hover effect makes it not not professional

### Add screenshots

https://github.com/user-attachments/assets/af9bf601-0104-4a64-be4e-24872153f5ff

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vishvboda** [comment]
I will add smooth animation on hover to this div and change hover effect on buttons.
Can you please assign this task under GSSoc'24 ext ?

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support**: If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!
