### ISSUE TITLE
[style]: 

### ISSUE THREAD

**Issue by mrpeace07** [codeaashu/DevDisplay#183]
### What's the style idea?

in the new feature oppurtun ity hub toggle icon to change the styling from light to dark or improving the ui based on these changes can be done

### Add screenshots

Add screenshots

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by mrpeace07** [comment]
![Screenshot 2024-10-08 111534](https://github.com/user-attachments/assets/9765e6d2-5e83-4866-80f7-15a7e97ebd47)
![Screenshot 2024-10-08 111540](https://github.com/user-attachments/assets/b251fead-29b8-45e3-a017-fc4f0265fae7)

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support**: If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!
