### ISSUE TITLE
[Feat]:  Added Authentication on several routes example opportunities hub

### ISSUE THREAD

**Issue by PARVNEMA** [codeaashu/DevDisplay#187]
### What feature?

implement authentication on some routes like opportunities hub etc you can implement it with appwrite or clerk or any other way you want  and it must be flexible so that we can add other routes for future authenticaiton

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by w0wayush** [comment]
Assign this task to me and please elaborate more what you want

**Comment by PARVNEMA** [comment]
@codeaashu  please assign the issue to @w0wayush  and for authentication he will be using clerk a reliable third party authentication library

**Comment by w0wayush** [comment]
Where do you want the Login Button on the website as the page don't have a navbar it would be better to add it on the Sidebar along with all the other buttons.

**Comment by PARVNEMA** [comment]
@w0wayush  yeah it would be better to implement login and signup on sidebar

**Comment by w0wayush** [comment]
Okay I would do that then @PARVNEMA 

Assign this task to me.

**Comment by PARVNEMA** [comment]
@w0wayush  you will be assigned by @codeaashu

**Comment by PARVNEMA** [comment]
@w0wayush  ok if you need my help at any point tell me

**Comment by codeaashu** [comment]
hello guys, @PARVNEMA  @w0wayush 

Ayush sorry for that bro
Just join this WhatsApp community of DevDisplay we all discuss where properly 

Community link -  https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4

**Comment by PARVNEMA** [comment]
@w0wayush  please join the whatsApp community soon

**Comment by w0wayush** [comment]
I have joined the community.

**Comment by PARVNEMA** [comment]
So we can start working on auth

**Comment by PARVNEMA** [comment]
@w0wayush  so did you added clerk auth ?

**Comment by w0wayush** [comment]
@PARVNEMA I'm currently working on it, but it may take a bit of time due to my college submissions. Is that okay with you?

**Comment by PARVNEMA** [comment]
@w0wayush  it's totally fine if you need my help tell me

**Comment by w0wayush** [comment]
For sure bro 👍😊

**Comment by w0wayush** [comment]
@PARVNEMA I can't find your number in WhatsApp. Where should I ask for suggestions?? Which group should I join for suggestion??

# Which one should be done 
- Modal for Signin / Signup 
Preview - https://github.com/user-attachments/assets/f8c792e5-7557-443b-a41f-01c2acc7138b

- Redirect to different page 
Preview - https://github.com/user-attachments/assets/12c7c18c-e9e1-4f16-874d-3b6ce8023263

Also tell me where I should place the userIcon after login for now I have placed in after search bar. If there are any changes needed suggest me.

**Comment by PARVNEMA** [comment]
@w0wayush  i like the first one

**Comment by PARVNEMA** [comment]
Community link - https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4 this is the channel in development team

**Comment by w0wayush** [comment]
I have already joined that

**Comment by w0wayush** [comment]
> @w0wayush i like the first one

Will do that one then.
Should I change anything other than that??
Like userIcon button which I placed at the right of Search bar

- Mobile View 
![image](https://github.com/user-attachments/assets/c78d09d8-80fa-4ace-9733-77d1ce41485a)


-Desktop View 
![image](https://github.com/user-attachments/assets/a82f5b24-4c5b-4e08-ac85-e2c69bc9d8ff)

**Comment by PARVNEMA** [comment]
Everything is fine

**Comment by w0wayush** [comment]
PR create kardu kya phir ??

**Comment by PARVNEMA** [comment]
Abhi ruk jaa @codeaashu  bhai dekhna theek lag rha hai signin sign up kya

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support**: If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!

**Comment by w0wayush** [comment]
@PARVNEMA after not getting response from @codeaashu I have created PR #218 you can check and verify if needed any changes to be made.

**Comment by PARVNEMA** [comment]
Ok @w0wayush
