### ISSUE TITLE
[Feat]: Create the Add profile page

### ISSUE THREAD

**Issue by Hh440** [codeaashu/DevDisplay#193]
### What feature?

How about creating a responsive profile addition page to enhance the website's user experience? By optimizing the design for all devices, users can seamlessly update their profiles, ensuring a smooth and engaging interaction. This will elevate both usability and overall satisfaction.

### Add screenshots

![Screenshot from 2024-10-09 11-11-19](https://github.com/user-attachments/assets/bd9f0e13-626b-4e02-beba-003666340f13)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support**: If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!

**Comment by Hh440** [comment]
@ishap11 please assign me this so i can start working on this
