### ISSUE TITLE
[style]: Changing the layout of the home page 

### ISSUE THREAD

**Issue by sanjeev0304** [codeaashu/DevDisplay#194]
### What's the style idea?

We need to improve  the layout of the page to vertical which is in Horizontal and add a NavBar
please assign me this issue I want to enhance the style of the webpage
Add the labels hactoberfest-accepted, Gssoc -ext24, Level 1/2/3
Best Regards
Sanjeev
Contributor

### Add screenshots

<img width="1470" alt="Screenshot 2024-10-09 at 12 05 18 PM" src="https://github.com/user-attachments/assets/96a6edcc-f208-4fa0-9eb4-d62597d6623b">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sanjeev0304** [comment]
@omkarvashistha 
Assign me this Issue

**Comment by omkarvashistha** [comment]
> @omkarvashistha Assign me this Issue

@sanjeev0304  I don't have required permissions to assign this issue , could you please check with someone who has the proper permissons

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support**: If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!
