### ISSUE TITLE
enhancing the side bar

### ISSUE THREAD

**Issue by mrpeace07** [codeaashu/DevDisplay#196]
### What's the style idea?

so basicaly chaninging the description written there and if in future there might be possibility of new features so giving ample space

### Add screenshots

![image](https://github.com/user-attachments/assets/6ae025f4-4a5f-448c-a317-d79f70c17104)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by omkarvashistha** [comment]
@codeaashu @mrpeace07 I am interested to work on this feature

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support**: If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!
