### ISSUE TITLE
[Feat]: adding light dark toggle button to oppurtunities

### ISSUE THREAD

**Issue by mrpeace07** [codeaashu/DevDisplay#197]
### What feature?

The Dark/Light theme toggle button allows users to easily switch between a bright and vibrant light mode and a calming dark mode. This feature enhances user experience by providing visual comfort in various lighting conditions, ensuring readability and reducing eye strain. With a simple click, users can personalize their interface, making it not only functional but also enjoyable to use. This flexibility reflects our commitment to accessibility and user-centric design, catering to individual preferences and enhancing overall engagement with the application

### Add screenshots

Add screenshots
![Screenshot 2024-10-08 111540](https://github.com/user-attachments/assets/8a82d58f-e73c-4317-9585-df3ca1f08d80)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by tushar-agarwal7** [comment]
@codeaashu  can u assgin this issue to me

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support**: If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!
