### ISSUE TITLE
Addition of links to Opportunities under Opportunities Hub and addition of effects on hovering the cards in Opportunities Hub

### ISSUE THREAD

**Issue by Shirisha-16** [codeaashu/DevDisplay#200]
i)Addition of links to cards
whenever we click on opportunities like internships, the page moves to the internship site showing all available internships, similarly to all other cards. 
![Screenshot 2024-10-09 192530](https://github.com/user-attachments/assets/95ef099c-3820-4f51-98fd-956e582189ce)
ii)addition of effects or changing of color on hovering the cards.

I want to work on this
@codeaashu assign me this task with the labels gssoc-ext, hacktoberfest-accepted and level according to the issue

**Comment by ishap11** [comment]
Hello @Shirisha-16, before diving into the features, please make sure to add your profile on DevDisplay. It’s the first priority for contributing to the project.

**Comment by Shirisha-16** [comment]
@ishap11 I am getting some error while adding my profile
![Screenshot 2024-10-10 131619](https://github.com/user-attachments/assets/0a510381-2895-46e8-9b2d-4ebfc16a49c1)
Please help me in this

**Comment by ishap11** [comment]
I noticed the issue and raised it as #202  because I thought we could solve it together. Why don’t you try to fix it first? If you get stuck, I’m here to help with some hints!

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support**: If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!

**Comment by codeaashu** [comment]
H
