### ISSUE TITLE
[Bug]: Fix GitHub Action Failure for Welcome Message in DevDisplay

### ISSUE THREAD

**Issue by ishap11** [codeaashu/DevDisplay#202]
### What happened?

I found a BUG 🐞
**Description**:
The welcome message GitHub Action, which is supposed to trigger when a user adds their profile to DevDisplay, is no longer working as expected. It was functioning properly when the project started, but now fails to execute during deployment.

**Steps to Reproduce**:
1. Add a profile to DevDisplay.
2. Expect a welcome message to be triggered via GitHub Action.
3. Observe that the action fails to send the message.

**Expected Behavior:** When a user adds their profile, they should receive a welcome message through GitHub.

**Actual Behavior**: No message is triggered, and the GitHub Action fails during deployment.

**Help Needed:** If anyone with experience in GitHub Actions can investigate and fix this issue, your contribution would be greatly appreciated!

### Add screenshots

![image](https://github.com/user-attachments/assets/9605947e-59ef-48b2-8f67-f76c9b50bf24)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by avishek999** [comment]
assign me this please

**Comment by omkarvashistha** [comment]
I think this issue might be coming because in github action file we do not have a condition for when the PR gets merged which means the user is added to DevDisplay

so maybe giving this condition might help

`if:  github.event.pull_request.merged == true && startsWith(github.event.pull_request.title, 'add : username:')`

**Note : instead of using PR title to identify we can change that condition also**

and also we should change `pull_request_target:` to `pull_request` as this is more secure

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support**: If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!

**Comment by ishap11** [comment]
Hi @avishek999,
Any updates on the GitHub Action bug regarding the welcome message? Let me know if you need any help.
