### ISSUE TITLE
[Bug]: Links Not Clickable on Website

### ISSUE THREAD

**Issue by AdityaP700** [codeaashu/DevDisplay#205]
### What happened?

I found a BUG 🐞
## Overview
I found out an issue in the Opportunities Hub Section in which the links which is provided aren't clickable in nature meaning that they are unable to redirect this to the respective site links Provided. Thus i can Fix the issue by identifying the key bug in this . 

### Add screenshots

![Screenshot 2024-10-10 194152](https://github.com/user-attachments/assets/66d957e2-c2f5-4c33-83d5-a948efd3f6ee)

### What browsers are you seeing the problem on?

Brave

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AdityaP700** [comment]
Kindly Look into this Issue and do let me assign me to fix this issue under HackOctoberFest and GSSOC-extd under any Level. Thanks in Anticipation

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support**: If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!

**Comment by codeaashu** [comment]
Hey @AdityaP700 

We're invited you to work on the issue on Opportunity page 
make all the link clickable our team will help you in the providing the main link through you can make it clickable 

Let's work on this issue and become a DevDisplay's core Team Member
