### ISSUE TITLE
[Feat]: Add Confirmation Message and Check Mark on Newsletter Subscription

### ISSUE THREAD

**Issue by AdityaP700** [codeaashu/DevDisplay#206]
## Description
When a user clicks the "Subscribe" button in the newsletter section, the system should display a confirmation message, along with a check mark, to notify the user that they have successfully subscribed. This will improve user feedback and enhance the subscription experience.
UI Changes:
## Overview
Once the "Subscribe" button is clicked, replace the button text with a confirmation message such as: “You are subscribed! ✅”.
or changing the button style (color, background) to visually indicate that the user has successfully subscribed.

### Add screenshots

Add screenshots
![Screenshot 2024-10-10 194310](https://github.com/user-attachments/assets/90adf430-f2ec-47bc-bf20-f3026dabfff8)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AdityaP700** [comment]
Kindly Look into the issue and let me assign to work on this issue under GSSOC-extd and HackOctoberFest tag under any Level . Thanks in Anticipation :)

**Comment by RohithNair27** [comment]
Hello. I am new and would love to contribute.
I would like to add this enhancement, if no one is already on it.

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support**: If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!
