### ISSUE TITLE
[Feat]: 'About Us' section in the side bar

### ISSUE THREAD

**Issue by darshinihoney** [codeaashu/DevDisplay#212]
### What feature?

The About Us section in the sidebar provides users with a quick overview of the platform’s mission, purpose, and values, ensuring transparency and trust. It offers a concise description and includes a link to a more detailed page for users who want to learn more.

### Add screenshots

![Screenshot 2024-10-11 170024](https://github.com/user-attachments/assets/6706af7c-577c-4263-95f1-99257cb67a5a)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codeaashu** [comment]
amazing work @darshinihoney 
but before that add your profile on DevDisplay
It's is the first priority of contribution in DevDisplay

if you don't assign in this you will not be able to contribute on this project

& also join the WhatsApp community 
https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4

**Comment by omkarvashistha** [comment]
@codeaashu  @darshinihoney I am interested to work on this issue , do you require any help on this.?

**Comment by darshinihoney** [comment]
> amazing work @darshinihoney but before that add your profile on DevDisplay It's is the first priority of contribution in DevDisplay
> 
> if you don't assign in this you will not be able to contribute on this project
> 
> & also join the WhatsApp community https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4

I have added my profile and thank you for assigning to me.

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support**: If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!
