### ISSUE TITLE
[Bug]: Improve Email Validation & Add Missing ID/Name to Subscribe Form Field

### ISSUE THREAD

**Issue by jatinkaushik-jk** [codeaashu/DevDisplay#214]
### What happened?

I found a BUG 🐞

### The "Subscribe with Email" form on the Opportunities page has two issues:

- The email field lacks an id or name attribute.
- Email validation allows invalid inputs like "example@email" without proper domain extensions (e.g., ".com", ".in").

**Steps to Reproduce:**
1. Navigate to the Opportunities page.
2. Enter an invalid email such as "example@email" in the subscription field.

**Expected Behavior:**
- The form should validate proper email formats (e.g., regex pattern requiring domain extensions like ".com").
- The email input field should have an `id` or `name` attribute for better accessibility.

**Proposed Solution:**
- Add proper `id` or `name` to the email field.
- Implement or update regex to validate email formats that include domain extensions (e.g., `^[\w\.-]+@[\w\.-]+\.\w{2,}$`).

### Add screenshots

![DevDisplay-Bug](https://github.com/user-attachments/assets/291d7571-95b9-4acc-a76a-b2177d9e1400)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Brave

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support**: If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!
