### ISSUE TITLE
[Feat]: Adding Social Media Icons to User Profiles

### ISSUE THREAD

**Issue by priyachau12** [codeaashu/DevDisplay#222]
### What feature?

I would like to propose adding social media icons to user profiles, including links for leetcode Profile ,Instagram, GeeksforGeeks (GFG), and CodeChef. This enhancement would allow users to easily connect and showcase their profiles across different platforms, fostering better networking and collaboration within the community.

Why is this feature needed?

Increased Visibility: Users can share their professional presence on platforms like LinkedIn, helping others to learn more about their experience and skills.
Community Engagement: Adding links to GFG and CodeChef can encourage collaboration and participation in coding challenges and discussions, enhancing the learning experience.
Personal Branding: Users can promote their personal projects and initiatives through Instagram, further showcasing their skills and interests.

### Add screenshots

Add screenshots
![image](https://github.com/user-attachments/assets/b43f74b9-3116-4a3a-8014-af4f69378f12)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support**: If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!
