### ISSUE TITLE
Adding a Feature to Connect on a Video Call for Guidance

### ISSUE THREAD

**Issue by priyachau12** [codeaashu/DevDisplay#223]
### What feature?

I propose adding a feature that allows users to connect on video calls for guidance and mentorship. This feature would enable members to schedule one-on-one or group video sessions to seek advice, collaborate, or discuss projects.

Why is this feature needed?

Personalized Guidance: Many developers benefit from personalized support and mentorship, and video calls offer a more effective way to communicate than text-based chat.
Enhanced Collaboration: This feature would facilitate real-time collaboration among developers, improving teamwork and project outcomes.
Community Building: Video calls can help foster a sense of community by allowing members to connect on a deeper level.
It can be paid too!

### Add screenshots

Add screenshots
Something like this:  
![image](https://github.com/user-attachments/assets/bd21082c-d312-45f2-bebf-73e9f00eb999)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support**: If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!

**Comment by codeaashu** [comment]
Hey @priyachau12 , Let's start working on this issue.
& be a part of core team of our organization.
