### ISSUE TITLE
[Feat]: No Back to Home Page Button | Enhancing the Styling of Card | In Opportunities Page

### ISSUE THREAD

**Issue by Shariq2003** [codeaashu/DevDisplay#260]
### Description 

1. There is no Back to top Button, to go back to devdisplay main page.
2. No Hover Effect on Card.

We need to improve the card styling

### Add screenshots

https://github.com/user-attachments/assets/3351e67c-389e-4c5b-9fe9-f987068c2e80

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HarshitaJaiswal5** [comment]
I am interested to work on this issue . Can you assign it to me under hacktoberfest ? @codeaashu
