### ISSUE TITLE
[Feat]: Add Contributor/ Team Page with real-time data fetching

### ISSUE THREAD

**Issue by Prathameshzad** [codeaashu/DevDisplay#269]
### What feature?

The Contributor/Team Page serves as a dynamic showcase of the talented individuals behind the project. By leveraging real-time data fetching, the page ensures that users always have access to the most up-to-date information about team members, fostering transparency and connection. The inclusion of search and filter options enhances usability, making it easy for visitors to find specific contributors. Through this implementation, we aim to create an engaging and informative experience that highlights the collaborative nature of the project while maintaining a modern and responsive design.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codeaashu** [comment]
Hey @Prathameshzad  let's start work on this features
and become a DevDisplay organization's core team member
