### ISSUE TITLE
[Docs]: add featured in table in main readme.md file

### ISSUE THREAD

**Issue by tarunkumar2005** [codeaashu/DevDisplay#287]
### what's wrong in the documentation?

The task involves updating the main README.md file to include a table highlighting project participation in open source program.

something like this

![image](https://github.com/user-attachments/assets/dd6810c9-58a2-4610-96b4-f397ef5c5829)

@codeaashu  Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by opbot-xd** [comment]
Can this issue be assigned to me?
