### ISSUE TITLE
[Feat]: Add Profile - AnanteshG

### ISSUE THREAD

**Issue by AnanteshG** [codeaashu/DevDisplay#296]
### What feature?

Would love to add my profile to the DevDisplay website

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ishap11** [comment]
Hi @AnanteshG , could you please star the repo? It would really help support the project!

**Comment by AnanteshG** [comment]
Done!
