### ISSUE TITLE
[Feat]: Add my profile to the web

### ISSUE THREAD

**Issue by Annapoornaaradhya** [codeaashu/DevDisplay#297]
### What feature?

I have an idea To add My Profile and Contribute
Please assign this issue under gssoc-ext and hacktoberfest-accecpted

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ishap11** [comment]
Hi @Annapoornaaradhya, could you please star the repo? It would really help support the project!

**Comment by Annapoornaaradhya** [comment]
I have!
Thank you for assigning the issue
