### ISSUE TITLE
[style]: Improve the Button Placement for "Add Your Profile", "Opportunity Hub", "Spotlight", and "Connect"

### ISSUE THREAD

**Issue by Utkarshrajmishra** [codeaashu/DevDisplay#302]
### What's the style idea?

The current placement of the buttons "Add Your Profile", "Opportunity Hub", "Spotlight", and "Connect" is not visually appealing and impacts the user experience. The buttons feel misaligned and cluttered, making the interface look unorganized.
The buttons should be placed in a way that enhances visual appeal and aligns with the design aesthetics of the page. This would provide a better user experience by improving readability and navigation.

### Add screenshots

![Screenshot from 2024-10-17 20-20-54](https://github.com/user-attachments/assets/54fc4f8d-3067-4477-b7bf-fa6469cbda13)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by irshadsiddi** [comment]
@Utkarshrajmishra ,I wanna work on this issue .please assign it to me

**Comment by Utkarshrajmishra** [comment]
@irshadsiddi, I am working on this.

**Comment by irshadsiddi** [comment]
@Utkarshrajmishra my bad carry on

**Comment by Utkarshrajmishra** [comment]
Hey @irshadsiddi, can you please assign it to me?
