### ISSUE TITLE
[Feat]: Add My Profile

### ISSUE THREAD

**Issue by Bhum-ika** [codeaashu/DevDisplay#309]
### What feature?

I would like to add my profile

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by madhukalita** [comment]
Hi @Bhum-ika , thanks for your interest in contributing to DevDisplay!

You will be assigned now add you profile here and be sure to star the DevDisplay GitHub Repository. 🌟

💌 This is a mandatory step for all contributors. & It's is the first priority of contribution in DevDisplay 💌

🚀 We look forward to your contribution once these steps are completed. 🚀

Thanks 👍🏻
