### ISSUE TITLE
[Bug]: Showing same person profile two times

### ISSUE THREAD

**Issue by shubhcoding01** [codeaashu/DevDisplay#314]
### What happened?

I found a BUG 🐞 On the [specific webpage or section] of the development display site, user profiles are erroneously appearing twice. This issue affects the visibility and usability of user data, potentially causing confusion for users.

Expected Behavior: Each user profile should only be displayed once.

Actual Behavior: The same user profile appears twice, leading to redundancy and possible user confusion.
![Screenshot 2024-10-18 201343](https://github.com/user-attachments/assets/9e68dabf-0f91-4643-a302-0257a22cf699)

**Comment by madhukalita** [comment]
Thanks @shubhcoding01  for find out this error
it's solved

Join DevDisplay Whatsapp community's Bug bounting group for future bug finding in DevDisplay
https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4

Thanks
