### ISSUE TITLE
[Feat]: There is no back button on opportunities page.

### ISSUE THREAD

**Issue by VinayLodhi1712** [codeaashu/DevDisplay#324]
### What feature?

I have an idea to add back button on opportunites page so user because it is a good user experience so that user does not need to use chrome default button to go back.

### Add screenshots

Add screenshots
![uttonbac](https://github.com/user-attachments/assets/f640d464-351b-4f33-b824-019cab17df89)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codeaashu** [comment]
let's start work in this issue
but before that add your profile here
