### ISSUE TITLE
I want to add my profile here.

### ISSUE THREAD

**Issue by Rupali1104** [codeaashu/DevDisplay#327]
- Please do assign it to me so that i can contribute to DevDisplay.
- I will follow the Rules and code of Conduct.
- Add the labels Gssoc-ext and Hacktoberfest.

**Comment by madhukalita** [comment]
Hi @Rupali1104 , thanks for your interest in contributing to DevDisplay!

You will be assigned now add you profile here and be sure to star the DevDisplay GitHub Repository. 🌟

💌 This is a mandatory step for all contributors. & It's is the first priority of contribution in DevDisplay 💌

🚀 We look forward to your contribution once these steps are completed. 🚀

Thanks 👍🏻
