### ISSUE TITLE
[Feat]: I want  add some extention to search feature

### ISSUE THREAD

**Issue by Sambashivarao-Boyina** [codeaashu/DevDisplay#330]
### What feature?

I have an idea to improve the search feature even more.
Present in skills criteria we can search only one skill at a time. so we can search for users with multiple skills at a time with a single input box 

I can do this feature. I have already implemented it in my e-commerce website so users can filter products in different categories simultaneously.

please assign this issue to me under gssoc-ext for

### Add screenshots

![Screenshot from 2024-10-19 17-30-27](https://github.com/user-attachments/assets/ba580aea-9175-4543-8c29-9f4dc3486dff)

so below we cannot see users when I search for multiple skills

![Screenshot from 2024-10-19 17-30-41](https://github.com/user-attachments/assets/53ee59f3-cd2c-472a-8d8e-e45e9f5bd4cf)

- Please assign it to me so that I can contribute to DevDisplay.
- I will follow the Rules and code of Conduct.
- Add the labels Gssoc-ext and Hacktoberfest.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by madhukalita** [comment]
Before raising any issue, please add you profile here and be sure to star the DevDisplay GitHub Repository. 🌟

💌 This is a mandatory step for all contributors. & It's is the first priority of contribution in DevDisplay 💌

🚀 We look forward to your contribution once these steps are completed. 🚀

Thanks 👍🏻

**Comment by Sambashivarao-Boyina** [comment]
I have completed the feature, I have tested it and it is working well, I have also created the pull request #414.  

could please review the code give me feedback and also add the labels of **gssoc-ext**, **hacktoberfest2024**, **level2**
