### ISSUE TITLE
[Feat]: Scroll to top feature

### ISSUE THREAD

**Issue by meghanakn473** [codeaashu/DevDisplay#339]
### What feature?

scroll to top button in the bottom right corner helps user to move to top of page easily
 @codeaashu  please assign me this issue i want to work on it
also add level 3, gssoc-extd, hacktoberfest labels

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by madhukalita** [comment]
share the video for better understanding of issue

**Comment by meghanakn473** [comment]
> share the video for better understanding of issue


https://github.com/user-attachments/assets/ba02e156-a1f1-498d-8225-70095df4fe36

in this way i want to implement
@madhukalita

**Comment by meghanakn473** [comment]
@madhukalita please check and assign me the issue

**Comment by codeaashu** [comment]
first add your profile here
