### ISSUE TITLE
[Feat]: I want to add my profile here

### ISSUE THREAD

**Issue by n14rishitha** [codeaashu/DevDisplay#340]
### What feature?

I have an idea 

### Add screenshots

Add screenshots
[
![Screenshot 2024-10-20 174427](https://github.com/user-attachments/assets/e1c180de-4d36-40a6-a523-0397227b9f2e)
](url)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by n14rishitha** [comment]
@codeaashu assign this to me

**Comment by madhukalita** [comment]
Hi @n14rishitha , thanks for your interest in contributing to DevDisplay!

You will be assigned now add you profile here and be sure to star the DevDisplay GitHub Repository. 🌟

💌 This is a mandatory step for all contributors. & It's is the first priority of contribution in DevDisplay 💌

🚀 We look forward to your contribution once these steps are completed. 🚀

Thanks 👍🏻
