### ISSUE TITLE
I want to add my Profile

### ISSUE THREAD

**Issue by 22Rupesh** [codeaashu/DevDisplay#348]
What's feature ?
I want to add my profile to  DevDisplay

ADD ScreenShots

![Screenshot 2024-10-20 203120](https://github.com/user-attachments/assets/937ba98b-586b-429e-8b38-f38bdb24a2d9)

**Comment by 22Rupesh** [comment]
@codeaashu please assigned me

**Comment by madhukalita** [comment]
Hi @22Rupesh , thanks for your interest in contributing to DevDisplay!

Before we proceed, please add you profile here and be sure to star the DevDisplay GitHub Repository. 🌟

💌 This is a mandatory step for all contributors. & It's is the first priority of contribution in DevDisplay 💌

🚀 We look forward to your contribution once these steps are completed. 🚀

Thanks 👍🏻
