### ISSUE TITLE
[Feat]: I want to add my profile on DevDisplay

### ISSUE THREAD

**Issue by AryanMittal11** [codeaashu/DevDisplay#361]
### What feature?

I want to add my profile on DevDisplay

### Add screenshots

Add screenshots
![Screenshot 2024-10-21 160219](https://github.com/user-attachments/assets/d564e251-4422-4192-9487-290e9331d406)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AryanMittal11** [comment]
@codeaashu please assign me

**Comment by madhukalita** [comment]
Hi @AryanMittal11 , thanks for your interest in contributing to DevDisplay!

Before we proceed, please add you profile here and be sure to star the DevDisplay GitHub Repository. 🌟

💌 This is a mandatory step for all contributors. & It's is the first priority of contribution in DevDisplay 💌

🚀 We look forward to your contribution once these steps are completed. 🚀

Thanks 👍🏻
