### ISSUE TITLE
[Feat]: I want to add my profile

### ISSUE THREAD

**Issue by 10m4y** [codeaashu/DevDisplay#366]
### What feature?

I have an idea 

### Add screenshots

Add screenshots

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by 10m4y** [comment]
Can  u label it with hacktoberfest and assign it to me

**Comment by ishap11** [comment]
Hi @cypher4802 , thanks for your interest in contributing to DevDisplay!

You will be assigned now add you profile here and be sure to star the DevDisplay GitHub Repository. 🌟

💌 This is a mandatory step for all contributors. & It's is the first priority of contribution in DevDisplay 💌

🚀 We look forward to your contribution once these steps are completed. 🚀

Thanks 👍🏻
