### ISSUE TITLE
[Feat]: Update skill search functionality

### ISSUE THREAD

**Issue by RNAdvani** [codeaashu/DevDisplay#369]
### What feature?

Instead of user manually typing a skill, we allow the user to click on the skills scrolling and that skill would be in the search bar and user can efficiently search

if you like this feature, assign this to me

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RNAdvani** [comment]
@codeaashu if you like this assign it to me

**Comment by codeaashu** [comment]
let's start work in this issue but before that add your profile here
