### ISSUE TITLE
[Feat]: I want to add my profile to dev display.

### ISSUE THREAD

**Issue by Rish6392** [codeaashu/DevDisplay#392]
### What feature?

I have an idea 

### Add screenshots

Add screenshots

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by ishap11** [comment]
Hi @Rish6392  , thanks for your interest in contributing to DevDisplay!

Before we proceed, we noticed you adding your profile on #DevDisplay but forgot to star the repo. It's like making an amazing sandwich and forgetting to take a bite! -- I think our repo's feeling a little lonely without your 🤗 So, be sure to star the DevDisplay GitHub Repository. 🌟

💌 This is a mandatory step for all contributors. & It's is the first priority of contribution in DevDisplay 💌

🚀 We look forward to your contribution once these steps are completed. 🚀

Thanks 👍🏻
