### ISSUE TITLE
[Docs]: 📝[DOCS] adding Stargazers and Forkers section to readme.md

### ISSUE THREAD

**Issue by amiya-cyber** [codeaashu/DevDisplay#410]
### what's wrong in the documentation?

We need to add Stargazers and Forkers section to readme.md

adding Stargazers and Forkers section to readme.md

Suggested Change

we can add Stargazers and Forkers section to readme.md

Stargazers

Use Case:

1. Bookmarking Projects
2. Discovering Popularity

Benefits:

1. Visibility
2. Feedback Indicator
3. Community Engagement

Forkers

Use Case:

1. Creating Personal Copies
2. Contributing Back

Benefits:

1. Encouraging Innovation
2. Easy Collaboration
3. Building Ownership

### Add screenshots

![2024-10-24](https://github.com/user-attachments/assets/bb794f92-efa5-4cf1-9ee8-f1480c7ad9ca)

ADD LABELS HACKTOBERFEST AND GSSOC EXT 24 AND LEVEL 2 OR LEVEL 3
ASSIGN ME THE WORK
THANK YOU @codeaashu  !

### Code of Conduct

- [x ] I agree to follow this project's Code of Conduct

**Comment by Brijeshthummar02** [comment]
@ishap11 i can work on it. Assign me
