### ISSUE TITLE
[Feat]: I want to add my Account

### ISSUE THREAD

**Issue by Sambashivarao-Boyina** [codeaashu/DevDisplay#415]
### What feature?

I want add my Account to the website.  

please assign me this under gssoc-ext, hacktoberfest2024.  

### Add screenshots

Add screenshots

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by ishap11** [comment]
Hi @Sambashivarao-Boyina , thanks for your interest in contributing to DevDisplay!
Before we proceed, please add you profile here and be sure to star the DevDisplay GitHub Repository. 🌟
💌 This is a mandatory step for all contributors. & It's is the first priority of contribution in DevDisplay 💌
🚀 We look forward to your contribution once these steps are completed. 🚀

Thanks 👍🏻

**Comment by Sambashivarao-Boyina** [comment]
I have added my Profile and created pulled request #421, could you review it merge the code and add labels of **gssoc-ext**, **hacktoberfest2024**,**level1**
