### ISSUE TITLE
[Feat]:  Implement Custom 404 Error Page for Invalid URLs

### ISSUE THREAD

**Issue by RachitSahu26** [codeaashu/DevDisplay#419]
### What feature?

I have an idea 
I propose adding a custom 404 error page that will be displayed when users attempt to access an invalid or non-existent URL within the application. This page will improve user experience by providing clear feedback and options for navigating back to valid content.

Proposed Features:
A visually appealing 404 error page with a friendly message informing users that the page they are looking for cannot be found.
Navigation options, such as links to the homepage and popular sections of the site.
A search bar for users to find content directly from the error page.
Optional suggestions for similar or related content.

### Add screenshots

Add screenshots
![Screenshot (392)](https://github.com/user-attachments/assets/abcf2a71-06ac-4a6c-935f-b028bcd2f179)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CoderXYZ14** [comment]
@codeaashu please assign me this issue

**Comment by RachitSahu26** [comment]
@CoderXYZ14  hey you can not do this sorry for that i have forgetten this because i was working on another repo now i remmebred that  so i am going to work on it
