### ISSUE TITLE
[Feat]: I want to add Vocice Search Functionality 

### ISSUE THREAD

**Issue by Sambashivarao-Boyina** [codeaashu/DevDisplay#432]
### What feature?

I have an idea to create a voice search for the user. so It make user to easily search the profiles.

Could you please assign this to me under the **gssoc-ext**, **hacktober-fest**.

### Add screenshots

![Screenshot from 2024-10-26 14-48-10](https://github.com/user-attachments/assets/3288f741-c7a4-4b40-89ef-da65211821b4)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by madhukalita** [comment]
Let's start

**Comment by Sambashivarao-Boyina** [comment]
Yeah definitely, Could you please give me **level2** for this

**Comment by madhukalita** [comment]
done

**Comment by Sambashivarao-Boyina** [comment]
I have completed the voice search feature and also make the pull request of the code #458 . I have test the code, could you please see the code and check the any error are there and send me the feedback. 

If it is okay merge code and assign me the labels. 

Thank you
