### ISSUE TITLE
[style]: homepage UI

### ISSUE THREAD

**Issue by Sriiishtiiiii** [codeaashu/DevDisplay#445]
### What's the style idea?

We need to improve the way these profiles are shown. Instead of showing them in an array based scrolled down itemlist, we can also display them in the form of cards with the photo in the center, the name and location below the profile image and the skills right below it. Once you click on the card anywhere, you are redirected to their github profiles.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Aditya-PS-05** [comment]
Can you assign me this issue under `GSSoc` and `hacktoberfest` label?

**Comment by Sriiishtiiiii** [comment]
I am myself interested to work upon this issue. Would be obliged to get assigned under hacktoberfest and GSSoc labels.

**Comment by codeaashu** [comment]
> I am myself interested to work upon this issue. Would be obliged to get assigned under hacktoberfest and GSSoc labels.

Hi @SrishtiChamoli , thanks for your interest in contributing to DevDisplay!

Before we proceed, please add you profile here and be sure to star the DevDisplay GitHub Repository. 🌟

💌 This is a mandatory step for all contributors. & It's is the first priority of contribution in DevDisplay 💌
🚀 We look forward to your contribution once these steps are completed. 🚀

Thanks 👍🏻

**Comment by Aditya-PS-05** [comment]
@codeaashu , please review my pr.

**Comment by Sriiishtiiiii** [comment]
@codeaashu , I've issued a PR as well. Would be grateful if u reviewed it!

**Comment by Sriiishtiiiii** [comment]
I’ve issued a PR for this issue. Would you please review it?
