### ISSUE TITLE
[style]: Responsive Header and Toggle Button Adjustment for Tablet View

### ISSUE THREAD

**Issue by shivhere007** [codeaashu/DevDisplay#455]
### What's the style idea?

This update aims to enhance the user interface of the "DevDisplay" platform on tablet devices. Adjustments focus on aligning the header elements and optimizing the light/dark mode toggle button for screens with a max-width of 768px. These changes ensure that the header is clean, centered, and free of overflow issues while the toggle button remains accessible without crowding, providing a seamless experience for tablet users.

### Add screenshots

Add screenshots
![Screenshot 2024-10-27 151538](https://github.com/user-attachments/assets/a02e01a3-35bc-4b34-af98-76f38e59942d)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shivhere007** [comment]
Kindly assign this to me @codeaashu , @ishap11 .

**Comment by codeaashu** [comment]
let's start @shivhere007

**Comment by shivhere007** [comment]
I think there has been a mistake here. You didn't assign me the issue @codeaashu | @madhukalita | @ishap11 . You assigned yourself. Kindly assign it to me so that i can start the work.
