### ISSUE TITLE
[Feat]: make the opportunity hub page consistent 

### ISSUE THREAD

**Issue by AE-Hertz** [codeaashu/DevDisplay#472]
### What feature?

The current opportunity page doesnot have same effect as it has on desktop, I will make it happen to maintain the consistency and it looks good for the site.

Assign me this under hacktoberfest and gssoc-ext 

### Add screenshots

Add screenshots
![1000016694](https://github.com/user-attachments/assets/4b38ace6-10a4-4bb8-9ffb-903b25638e7d)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codeaashu** [comment]
Check out the #issue475 ⬇
https://github.com/codeaashu/DevDisplay/issues/475#issue-2617410305

Get a #level3 on your open-source contribution.

Remember that ⚠ This issue will be closed on 31 October

**Comment by AE-Hertz** [comment]
@codeaashu i dont understand 475 , their is a issue with level 3 already assigned to someone, as this issue is closed can you assign me issues please.
