### ISSUE TITLE
[Feat]:  I want to add my account 

### ISSUE THREAD

**Issue by Abhi0049k** [codeaashu/DevDisplay#478]
### What feature?

I have an idea 

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ishap11** [comment]
Hi @Abhi0049k , thanks for your interest in contributing to DevDisplay!

Before we proceed, please add you profile here and be sure to star the DevDisplay GitHub Repository. 🌟

💌 This is a mandatory step for all contributors. & It's is the first priority of contribution in DevDisplay 💌

🚀 We look forward to your contribution once these steps are completed. 🚀

Thanks 👍🏻
