### ISSUE TITLE
[Feat]: Development of TechDisplay Page and Home Page Setup

### ISSUE THREAD

**Issue by ishap11** [codeaashu/DevDisplay#479]
### What feature?

Hello, this is Isha Prajapati. I’d like to take on the task of developing the homepage and setting up the TechDisplay page, as mentioned in issue no. #475. I’d appreciate it if you could assign this to me.

Thank you!

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Musaveershaik** [comment]
@ishap11 Kindly assign me this task under Hacktoberfest2024, Thanku.

**Comment by ishap11** [comment]
Hello @Musaveershaik, could you please check issue #475 ? Choose any one of the features you'd like to add to DevDisplay, then create a new issue referencing the main issue number (#475).
