### ISSUE TITLE
🐞[Bug]: Uncaught Runtime Error Prevents Local Development

### ISSUE THREAD

**Issue by akash70629** [codeaashu/DevDisplay#489]
### What happened?

# I found a BUG 🐞

## Description:
After forking and cloning the repository, I encountered a major issue while setting up the local environment. Upon running npm install and npm start, I received an uncaught runtime error.
Impact: This critical bug prevents contributors from actively developing and contributing to the website.

## Steps to Reproduce:

1. Fork and clone the repository.
2. Run npm install to install dependencies.
3. Run npm start to start the application.

## Reason of the error 

The error indicates that the value stored in local storage under the key 'theme' is not valid JSON. Specifically, it seems that the value is a plain string (like "dark" or "light") rather than a JSON-encoded string.

## Additional Information
Urgent assistance is required to resolve this issue and ensure seamless local development.

### Add screenshots

![image](https://github.com/user-attachments/assets/5e8556be-23fc-4ab8-8870-068deece42e1)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by akash70629** [comment]
Please assign me this issue under gssoc level 2 tag.

**Comment by madhukalita** [comment]
Hi @ thanks for your interest in contributing to DevDisplay!

Now you will be assigned to solved this bug.
Start working on that issue 

Thanks 👍🏻

**Comment by akash70629** [comment]
Hey @codeaashu !!! PR is still open and unmerged!!!
