### ISSUE TITLE
[Feat]: I want to add Question and guideline section

### ISSUE THREAD

**Issue by souvikpramanikgit** [codeaashu/DevDisplay#500]
### What feature?

# ✨ Feature Request

### **Description of the Feature**

# GitHub Issue Creation Guidelines

When creating an issue in this repository, please follow these guidelines to ensure the process runs smoothly and efficiently. We also have additional resources to help guide you depending on the nature of your inquiry.

Before you create a new issue, consider the following options:

### 1. Questions or Need Suggestions?
If you're unsure whether to open an issue or if you need clarifications, suggestions, or help with a feature, please use our Q&A discussion section. You can create a new discussion under the **Q&A category**, and the community or maintainers will be able to assist you.

Creating a discussion instead of an issue helps:
- Engage the community for ideas or help.
- Keep the issue tracker focused on bugs and feature requests.
- Provide a space for conversation without needing a formal issue.

### 2. Guidelines
Please read our CONTRIBUTING.md file for detailed guidelines on how to create a meaningful issue or contribute to the project. Following the guidelines will ensure that:
- Your issue contains all the necessary information.
- It adheres to the project's standards, making it easier to process and address.
- It fits within the workflow of the project, reducing the chance of unnecessary back-and-forth.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/ecab3efb-7f50-40c2-9ddc-c3d0356a5e7d)

### Add screenshots

![image](https://github.com/user-attachments/assets/ecab3efb-7f50-40c2-9ddc-c3d0356a5e7d)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by madhukalita** [comment]
Hi @souvikpramanikgit  thanks for your interest in contributing to DevDisplay!

Now you will be assigned for this enhancement issue but **before we proceed, please add you profile here and be sure to star the DevDisplay GitHub Repository. 🌟**

💌 This is a mandatory step for all contributors. & It's is the first priority of contribution in DevDisplay 💌

🚀 We look forward to your contribution once these steps are completed. 🚀

Thanks 👍🏻
