### ISSUE TITLE
[Feat]: Adding Contributors page 

### ISSUE THREAD

**Issue by TBorundia** [codeaashu/DevDisplay#503]
### What feature?

I can add the option to navigate contributor page.
I will show the github profile of all the contributors worked for the project.
I will ensure to make the page UI similar to the theme and also responsive for all screens.
It will directly fetch the data from the repository.

It will show,
Transparency: It shows transparency in the project's development and highlights the collaborative effort behind it.
Engagement: It helps build a community by encouraging more people to contribute and get involved.
Networking: It provides an opportunity for users to connect with contributors, potentially leading to more collaboration and support.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by madhukalita** [comment]
Hi @TBorundia  thanks for your interest in contributing to DevDisplay!

Now you will be assigned for this enhancement issue but **before we proceed, please add you profile here and be sure to star the DevDisplay GitHub Repository. 🌟**

💌 This is a mandatory step for all contributors. & It's is the first priority of contribution in DevDisplay 💌

🚀 We look forward to your contribution once these steps are completed. 🚀

Thanks 👍🏻
