### ISSUE TITLE
[Docs]: Add security of the website

### ISSUE THREAD

**Issue by Dipanita45** [codeaashu/DevDisplay#512]
### what's wrong in the documentation?

We need to add Security

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by madhukalita** [comment]
Hi @Dipanita45 , thanks for your interest in contributing to DevDisplay!

Now you will be assigned for this enhancement issue but **before we proceed, please add you profile here and be sure to star the DevDisplay GitHub Repository. 🌟**

💌 This is a mandatory step for all contributors. & It's is the first priority of contribution in DevDisplay 💌

🚀 We look forward to your contribution once these steps are completed. 🚀

Thanks 👍🏻
