### ISSUE TITLE
[style]: Update the animation of Button

### ISSUE THREAD

**Issue by codeaashu** [codeaashu/DevDisplay#523]
### What's the style idea?

We need to improve  

Add this animation on Button "Unlock the Power of DevDisplay"
Animation link - [Button Animation](www.hover.dev/components/buttons#encrypt-button)

![download](https://github.com/user-attachments/assets/887de6ec-224d-451d-a52b-c92c38ade1d6)

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AkashJana18** [comment]
Hey @codeaashu i would like to work on this issue 
The button animation link is broken please provide a valid one

**Comment by codeaashu** [comment]
> Hey @codeaashu i would like to work on this issue The button animation link is broken please provide a valid one

www.hover.dev/components/buttons#encrypt-button

**Comment by codeaashu** [comment]
start working on this issue

**Comment by AkashJana18** [comment]
Couldn't start due to issue #529
