### ISSUE TITLE
[style]: Add a DevDisplay icon 

### ISSUE THREAD

**Issue by codeaashu** [codeaashu/DevDisplay#524]
### What's the style idea?

We need to improve  

Remove the  " </> "    Add a DevDisplay icon here
![Screenshot (1421)](https://github.com/user-attachments/assets/632defd8-9437-4cd1-8518-2f9fd9af9ad3)

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AkashJana18** [comment]
Hey @codeaashu we Just have to remove the logo or replace it?

**Comment by codeaashu** [comment]
> Hey @codeaashu we Just have to remove the logo or replace it?

Yes

**Comment by AkashJana18** [comment]
please assign me

**Comment by codeaashu** [comment]
start working on this issue

**Comment by AkashJana18** [comment]
Couldn't start due to  issue #529
