### ISSUE TITLE
[Feat]: Add scroll to top button 

### ISSUE THREAD

**Issue by souvikpramanikgit** [codeaashu/DevDisplay#541]
### What feature?

Add scroll to top button , which will help to move to the upside without wasting any time.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by madhukalita** [comment]
Hi @souvikpramanikgit, thanks for your interest in contributing to DevDisplay!

Now you will be assigned for this enhancement issue but **before we proceed, please add you profile here and be sure to star the DevDisplay GitHub Repository. 🌟**

💌 This is a mandatory step for all contributors. & It's is the first priority of contribution in DevDisplay 💌

🚀 We look forward to your contribution once these steps are completed. 🚀

Thanks 👍🏻
