### ISSUE TITLE
[Bug]: To improve the UI/UX of the dropdown and overall alignment of dropdown  on your page

### ISSUE THREAD

**Issue by Pragati1466** [codeaashu/DevDisplay#556]
### What happened?

The dropdown list for sorting (Name, Location, Skill) seems slightly detached or misaligned from the input field. It could be more visually cohesive.The user cards and their content could be better aligned to make them more visually balanced.
There could be some padding adjustments around text and icons to enhance readability and flow.

### Add screenshots

Add screenshots

### Code of Conduct

- [yes ] I agree to follow this project's Code of Conduct

**Comment by Pragati1466** [comment]
pls assign me under ieee-igdtuw
<img width="1538" alt="Screen Shot 2024-11-15 at 11 15 13 PM" src="https://github.com/user-attachments/assets/080abf0d-047a-414f-ba52-28d87ce95deb">

**Comment by codeaashu** [comment]
Hi @Pragati1466  thanks for your interest in contributing to DevDisplay!

Now you will be assigned for this enhancement issue but *before we proceed, please add you profile here and be sure to star the DevDisplay GitHub Repository. 🌟*

💌 This is a mandatory step for all contributors. & It's is the first priority of contribution in DevDisplay 💌

🚀 We look forward to your contribution once these steps are completed. 🚀

Thanks 👍🏻

**Comment by Pragati1466** [comment]
@codeaashu I am not able to find where dropdown is located ?so could you tell me which file

**Comment by codeaashu** [comment]
Hey @Pragati1466 -- leave that -- issues

If you want to contribute on Devdisplay and making an impact -- Focus on these listed Features 👇🏻

> https://www.devdisplay.org/ProjectShowcase
> https://www.devdisplay.org/Discussions
> https://www.devdisplay.org/IdeaSubmission
> https://www.devdisplay.org/PortfolioIdeas
> https://www.devdisplay.org/PortfolioBuilder
> https://www.devdisplay.org/ResumeBuilder

💌 It's not just a contribution. If you build any of these 6 features, you will be selected as a core team member of our community-based startup **DevDisplay**. Your work will shape the future of our developer community.
