### ISSUE TITLE
[Feat]: Add a 404 Not Found Page

### ISSUE THREAD

**Issue by Riddhi050803** [codeaashu/DevDisplay#558]
### What feature?

Description:
Currently, the website does not have a 404 Not Found page, and navigating to non-existent routes results in an unhandled or default error message. This issue aims to create and integrate a custom 404 Not Found page to enhance user experience by providing appropriate feedback for invalid routes.

Tasks:
Design a 404 Not Found page with the following features:

1. A user-friendly message indicating the page isn't available.
2. A button or link redirects the user to the homepage or other relevant pages.
3. Optional: Include visual elements like illustrations or animations for better UX.
4. Implement the page in the current project setup (React/Vite/other frameworks in use).

Configure the routing logic to render the 404 Not Found page for undefined routes.

### Add screenshots

![image](https://github.com/user-attachments/assets/5483c715-bbf0-4401-96be-d9dd9541b9b7)
Something similar

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Riddhi050803** [comment]
@codeaashu Assign this to me and kindly add ieee-igdtuw label.

**Comment by codeaashu** [comment]
Hey @Riddhi050803  Now you will be assigned Start working on this 

Apart from that, If you want to contribute on Devdisplay and making an impact -- Focus on these listed Features 👇🏻 
If you build any of these 6 features, you will be selected as a core team member of our community-based startup **DevDisplay**.  --- Shaping DevDisplay’s future as we rise to become a global leader in tech innovation.

> https://www.devdisplay.org/ProjectShowcase
> https://www.devdisplay.org/Discussions
> https://www.devdisplay.org/IdeaSubmission
> https://www.devdisplay.org/PortfolioIdeas
> https://www.devdisplay.org/PortfolioBuilder
> https://www.devdisplay.org/ResumeBuilder

Here’s your chance to be part of something groundbreaking from the very beginning. DevDisplay is on track to become a global tech hub, and we’re inviting you to be part of our journey!
