### ISSUE TITLE
[Bug]: greetings.yml is not correctly configured

### ISSUE THREAD

**Issue by harshsvaidya** [codeaashu/DevDisplay#660]
### What happened?

I found a BUG 🐞 such that when someone raise issue greetings.yml is not generating greeting message. 

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by harshsvaidya** [comment]
Assign this issue to me

**Comment by codeaashu** [comment]
Hey @harsh432004 

Actually, i just accepted your PR but this "greetings.yml" also not working till now.

check it out what's the problem is generated?
