### ISSUE TITLE
Fix Responsive Design Issue on MacBook View

### ISSUE THREAD

**Issue by codeaashu** [codeaashu/DevDisplay#81]
## Issue 

There is a responsiveness issue with the DevDisplay platform when viewed on a MacBook. The layout does not adjust correctly, causing elements to overlap and making the site difficult to navigate. This issue needs to be addressed to ensure a seamless user experience across all devices.

### Steps to Reproduce

1. Open the DevDisplay site on a MacBook.
2. Observe the layout issues such as overlapping elements and misaligned content.

### Expected Behavior

The layout should adjust fluidly to the MacBook screen size, ensuring all elements are properly aligned and the site is fully navigable without any visual issues.

### Screenshots

Attached below are the screenshots illustrating the issue:

<img width="900" alt="issues 1 - Responsive on macbook view " src="https://github.com/user-attachments/assets/4c2bc0ed-1600-411f-9281-8df252f44c33"><hr>

### Additional Information
- **OS:** macOS [ In Every version ]

### How to Contribute

We welcome contributions from the open-source community to resolve this issue. Please follow the steps below to contribute:

1. Fork the repository from [DevDisplay GitHub Repository](https://github.com/codeaashu/DevDisplay).
2. Create a new branch for your fix: `git checkout -b fix-macbook-responsive`.
3. Commit your changes: `git commit -m 'Fix responsive design issue on MacBook view'`.
4. Push to the branch: `git push origin fix-macbook-responsive`.
5. Open a Pull Request describing your changes.

#### Description: By submitting this issue, you agree to follow our Code of Conduct

We appreciate your contributions to improving DevDisplay!

### Contact

For any questions or further information, please reach out to the project maintainers. @codeaashu 

Specially thanks to #hacktoberfest 2024
Thank you for helping us make #DevDisplay better!

**Comment by Zish303** [comment]
Hi,
I have understood the problem. I want to solve this issue for "Hacktoberfest".
Please assign it to me.

**Comment by PARVNEMA** [comment]
hello i am working on the issue and i am solving this for  "HacktoberFest" please assign me this

**Comment by PARVNEMA** [comment]
hello @codeaashu  sir i have fixed the design and this is my first pull request so could you please give me feedback about it and please add hacktoberfest label to it

**Comment by codeaashu** [comment]
Mail me with your personal email: hellow.ashutosh@gmail.com

**Comment by PARVNEMA** [comment]
My mail - namannema0704@gmail.com

**Comment by itznayan** [comment]
I would like to work on this issue kindly assign it to me under Gssoc'24 extended and Hacktoberfest.

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support**: If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!
