### ISSUE TITLE
[Feat]: to add a separate profile page 

### ISSUE THREAD

**Issue by Prathamesh0901** [codeaashu/DevDisplay#89]
### What feature?

whenever we click on view profile or the users name, it redirects us to the github profile of the user. instead it would be great if we redirect them to dedicated profile page of devdisplay where all the information of the user will be displayed.
I am open to work on this

### Add screenshots

Add screenshots

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by codeaashu** [comment]
mail me on this : hellow.ashutosh@gmail.com

**Comment by shreyamaheshwari1** [comment]
@codeaashu I would like to work on this if this issue is still open under the hactoberfest-extended and gssoc label . I can create a designated profile page for the user.

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support**: If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!

**Comment by codeaashu** [comment]
Check out the #issue475 ⬇
https://github.com/codeaashu/DevDisplay/issues/475#issue-2617410305

Get a #level3 on your open-source contribution.

Remember that ⚠ This issue will be closed on 31 October
