### ISSUE TITLE
[Feat]:  Add 'Star Us on GitHub' Button.

### ISSUE THREAD

**Issue by SCR01** [codeaashu/DevDisplay#91]
### What feature?

We would like to add a **'Star Us on GitHub**' button to the homepage of our platform.

This feature will encourage visitors and contributors to star our repository directly from the homepage, increasing our visibility and showing community support for the project.

 **Idea:**
- Add the button prominently on the homepage to increase interactions.
- The button should be clearly visible and styled consistently with the design of the website.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support:** If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!

**Comment by codeaashu** [comment]
Check out the #issue475 ⬇
https://github.com/codeaashu/DevDisplay/issues/475#issue-2617410305

Get a #level3 on your open-source contribution.

Remember that ⚠ This issue will be closed on 31 October

**Comment by AE-Hertz** [comment]
@codeaashu can you please assign me this?
