### ISSUE TITLE
Pagination Buttons Are Difficult to See and Use.

### ISSUE THREAD

**Issue by SCR01** [codeaashu/DevDisplay#92]
### What happened?

I found a BUG 🐞

### **Description:**
When navigating through profiles, the "Previous" and "Next" buttons for pagination are not as visible or user-friendly as expected. This may cause issues for users trying to explore a large number of profiles, particularly when looking for specific expertise or connections.

**What Happened:**

- When browsing profiles, the pagination buttons at the bottom of the page ("Previous" and "Next") are difficult to notice.
- This results in users potentially missing the option to navigate to different pages or not understanding how to go back or forward easily.

**Expected Behavior:**

- Pagination buttons should be easily noticeable and more user-friendly.
- They should provide clear navigation cues and ensure that users can efficiently browse through profiles.

**Suggested Fix:**
Enhancement : Make pagination buttons more prominent (e.g., larger font, bright contrasting colors).

### Add screenshots

Add screenshots:

![Screenshot 2024-10-02 155103](https://github.com/user-attachments/assets/be84370a-bf87-4814-adcc-680306553b43)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codeaashu** [comment]
Hello Sharad,
Mail me on - ***@***.***

**Comment by SCR01** [comment]
@codeaashu showing this while mailing you. what to do??

![Screenshot 2024-10-02 165720](https://github.com/user-attachments/assets/2a1400b2-1206-4a70-acca-6f3eaf518e46)

**Comment by codeaashu** [comment]
whatsapp me on this number - 6209950346

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support**: If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!

**Comment by codeaashu** [comment]
Check out the #issue475 ⬇
https://github.com/codeaashu/DevDisplay/issues/475#issue-2617410305

Get a #level3 on your open-source contribution.

Remember that ⚠ This issue will be closed on 31 October

**Comment by AE-Hertz** [comment]
@codeaashu can you please assign me this?
