### ISSUE TITLE
 Store User Data in MongoDB Using Node.js and MongoDB Atlas and Modifying UI via REST API

### ISSUE THREAD

**Issue by samriddhitiwary** [codeaashu/DevDisplay#93]
### What feature?

We need to shift the data source of some of the users from raw JSON data to MongoDB Atlas by creating a backend using Node.js. The UI will be updated to retrieve data from the MongoDB database using a REST API. This transition will involve building a backend that manages database operations, including the creation, retrieval, updating, and deletion of accessory data.

Since that's lot of data it, **I will implement the above idea for few users** and then someone else can just put the data to manually by themselves.

Steps to Reproduce the Issue
Action 1: Set up a MongoDB Atlas cluster and create a collection for accessories.
Action 2: Develop a Node.js backend using Express to connect to MongoDB Atlas.
Action 3: Implement the REST API endpoints (GET, POST, PUT, DELETE) to manage accessory data.
Action 4: Modify the frontend to retrieve accessory data via the REST API, replacing the existing static JSON data.
Expected Behavior
The data should be retrieved dynamically from MongoDB Atlas.
The REST API should provide endpoints for managing accessory data (CRUD operations).
The frontend UI should display the data retrieved from the database, with no reliance on static JSON.

Actual Behavior
Currently, the data is being fetched from a static JSON file.
No backend system is in place to dynamically manage accessory data.
The UI is not connected to a REST API for retrieving or updating data.

### Add screenshots

Add screenshots
![image](https://github.com/user-attachments/assets/4b46202f-0cf7-4974-97e7-6d2e1260ba5e)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samriddhitiwary** [comment]
@codeaashu could you please assign this issue to me under GSSoC-exd and Hacktoberfest Label.

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support:** If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support**: If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!

**Comment by codeaashu** [comment]
Check out the #issue475 ⬇
https://github.com/codeaashu/DevDisplay/issues/475#issue-2617410305

Get a #level3 on your open-source contribution.

Remember that ⚠ This issue will be closed on 31 October
