### ISSUE TITLE
[Bug]: Theme Mode Does Not Follow Device Default Setting

### ISSUE THREAD

**Issue by mohit-2003** [codeaashu/DevDisplay#94]
### What happened?

I found a BUG 🐞
The website's theme mode (light/dark) is not automatically adjusting based on the device's default theme setting. Users have to manually switch between light and dark modes, which can lead to inconsistent user experience across devices.

**Proposed Solution:**
Implement functionality that detects the user's device default theme (light or dark) and automatically applies it to the website upon loading. This will provide a more seamless experience, aligning the website's appearance with the user's system preferences.

### Add screenshots

Add screenshots

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by amanpoddar-dev12** [comment]
I think we can use cookies to resolve this problem.

**Comment by Bgmi10** [comment]
https://github.com/user-attachments/assets/8c1422c4-fd1a-4bf6-8cac-ea322f94d04c

issue fixed

**Comment by mohit-2003** [comment]
Hey @Bgmi10, Let's suppose your device is in dark mode. Now you open first time this website then this website should be in dark mode by default. Is it working?

**Comment by Bgmi10** [comment]
working fine

**Comment by Bgmi10** [comment]
https://github.com/user-attachments/assets/3776229f-e236-474d-a9fe-9b461866e7ca

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support**: If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support**: If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!
