### ISSUE TITLE
[style]: Redesign Sidebar for Better UI/UX

### ISSUE THREAD

**Issue by khaulanauman** [codeaashu/DevDisplay#95]
### What's the style idea?

We need to improve the sidebar design to enhance its visual appeal and user experience. This will involve updating the layout, color scheme, spacing, and typography to ensure a clean, modern look. I plan to use Tailwind CSS for consistency. Kindly assign this issue to me under Hacktoberfest and GSSoC Ext 24.

### Add screenshots

![image](https://github.com/user-attachments/assets/6ec3cca8-62a7-4d16-9108-500b8783da1c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codeaashu** [comment]
mail me on : hellow.ashutosh@gmail.com

**Comment by AnklekarMahima** [comment]
@codeaashu I too would like to work on the design of the sidebar.
Please assign me this issue under Hacktoberfest and GSSoC Ext 24.

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support**: If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution**: If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!

**Comment by Vishrut99** [comment]
can you please assign me this ??

**Comment by khaulanauman** [comment]
Hi - im alr working on it
